CREATE TABLE IF NOT EXISTS public.member (
  id BIGSERIAL PRIMARY KEY,
  nation VARCHAR(20) NOT NULL CHECK (nation IN ('위나라', '촉나라', '오나라')),
  crew_name VARCHAR(50) NOT NULL,
  nickname VARCHAR(50) NOT NULL UNIQUE,
  role_name VARCHAR(50) NOT NULL DEFAULT '일반 병사',
  job VARCHAR(50),
  weapon INTEGER,
  helmet INTEGER,
  armor INTEGER,
  shoes INTEGER,
  soop_id VARCHAR(100) NOT NULL UNIQUE,
  is_live BOOLEAN NOT NULL DEFAULT FALSE,
  thumbnail_image_url TEXT,
  profile_image_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS member_nation_idx ON public.member (nation);
CREATE INDEX IF NOT EXISTS member_crew_name_idx ON public.member (crew_name);
CREATE INDEX IF NOT EXISTS member_role_name_idx ON public.member (role_name);

INSERT INTO public.member (
  nickname,
  soop_id,
  nation,
  crew_name,
  role_name,
  is_live,
  thumbnail_image_url,
  profile_image_url
)
VALUES
  ('조경훈', 'cnsgkcnehd74', '위나라', '버인협회', '군주', FALSE, NULL, NULL),
  ('표우', 'pyowoo', '위나라', '버인협회', '일반 병사', FALSE, NULL, NULL),
  ('해솔', 'liloolil', '위나라', '버인협회', '일반 병사', FALSE, NULL, NULL),
  ('윤이샘', 'yoonesaem', '위나라', '버인협회', '일반 병사', FALSE, NULL, NULL),
  ('비숑', 'merryou', '위나라', '버인협회', '일반 병사', FALSE, NULL, NULL),
  ('송소미', 'ry0135', '위나라', '버인협회', '일반 병사', FALSE, NULL, NULL),
  ('제리츄', 'rariruro', '위나라', '버인협회', '일반 병사', FALSE, NULL, NULL),
  ('뀨복', 'kkyubog', '위나라', '버인협회', '일반 병사', FALSE, NULL, NULL),
  ('김쁘피', 'gurm01', '위나라', '버인협회', '일반 병사', FALSE, NULL, NULL),
  ('박재박', 'jaeparkk', '위나라', '털즈란', '장군', FALSE, NULL, NULL),
  ('로기다', 'hrlim95', '위나라', '로스타시티', '장군', FALSE, NULL, NULL),
  ('추멘', 'e9dongsung', '위나라', '로스타시티', '일반 병사', FALSE, NULL, NULL),
  ('은초롱', 'eunchr', '위나라', '로스타시티', '일반 병사', FALSE, NULL, NULL),
  ('리피피', 'haeri001', '위나라', '로스타시티', '일반 병사', FALSE, NULL, NULL),
  ('시오', 'siioyeyo', '위나라', '로스타시티', '일반 병사', FALSE, NULL, NULL),
  ('푸마고치', 'fumagochi', '위나라', '로스타시티', '일반 병사', FALSE, NULL, NULL),
  ('쥬멩이', 'ju010228', '위나라', '로스타시티', '일반 병사', FALSE, NULL, NULL),
  ('온유일', 'oneon1y', '위나라', '로스타시티', '일반 병사', FALSE, NULL, NULL),
  ('찐랑', 'phs6162', '위나라', '로스타시티', '일반 병사', FALSE, NULL, NULL),
  ('아르르', 'cosmicaaarrr', '위나라', '로스타시티', '일반 병사', FALSE, NULL, NULL),
  ('감스트', 'devli0108', '촉나라', '버컴퍼니', '군주', FALSE, NULL, NULL),
  ('니니', 'honeys2', '촉나라', '버컴퍼니', '일반 병사', FALSE, NULL, NULL),
  ('단츄', 'danchu17', '촉나라', '버컴퍼니', '일반 병사', FALSE, NULL, NULL),
  ('달묘', 'nmohoho', '촉나라', '버컴퍼니', '일반 병사', FALSE, NULL, NULL),
  ('망구랑', 'nmangoquince', '촉나라', '버컴퍼니', '일반 병사', FALSE, NULL, NULL),
  ('바밍', 'qweasd3456', '촉나라', '버컴퍼니', '일반 병사', FALSE, NULL, NULL),
  ('부르', 'bureu2002', '촉나라', '버컴퍼니', '일반 병사', FALSE, NULL, NULL),
  ('설이', 'mini8282', '촉나라', '버컴퍼니', '일반 병사', FALSE, NULL, NULL),
  ('앙또', 'aangdoxx', '촉나라', '버컴퍼니', '일반 병사', FALSE, NULL, NULL),
  ('유설아', 'yeveee', '촉나라', '버컴퍼니', '일반 병사', FALSE, NULL, NULL),
  ('유연서', 'cctvno', '촉나라', '버컴퍼니', '일반 병사', FALSE, NULL, NULL),
  ('앨리스얌', 'alicehiyam', '촉나라', '버컴퍼니', '일반 병사', FALSE, NULL, NULL),
  ('킹냥이', 'sa5791', '촉나라', '버컴퍼니', '일반 병사', FALSE, NULL, NULL),
  ('킴나니', 'sksgml16', '촉나라', '버컴퍼니', '일반 병사', FALSE, NULL, NULL),
  ('해리', 'gofl2237', '촉나라', '버컴퍼니', '일반 병사', FALSE, NULL, NULL),
  ('꾸티뉴', 'aksen7833', '촉나라', '꾸한성', '장군', FALSE, NULL, NULL),
  ('김옥독', 'niniru', '촉나라', '꾸한성', '일반 병사', FALSE, NULL, NULL),
  ('난워니', 'whiteone325', '촉나라', '꾸한성', '일반 병사', FALSE, NULL, NULL),
  ('냥쏘', 'leesoi34', '촉나라', '꾸한성', '일반 병사', FALSE, NULL, NULL),
  ('다뮤', 'not15987', '촉나라', '꾸한성', '일반 병사', FALSE, NULL, NULL),
  ('딴딴2당', 'dbsk0708', '촉나라', '꾸한성', '일반 병사', FALSE, NULL, NULL),
  ('리카', 'lika07', '촉나라', '꾸한성', '일반 병사', FALSE, NULL, NULL),
  ('모야', 'neul0908', '촉나라', '꾸한성', '일반 병사', FALSE, NULL, NULL),
  ('바먀', 'wooyah21', '촉나라', '꾸한성', '일반 병사', FALSE, NULL, NULL),
  ('서라0', 'o0opha', '촉나라', '꾸한성', '일반 병사', FALSE, NULL, NULL),
  ('소심해', 'thtlago0607', '촉나라', '꾸한성', '일반 병사', FALSE, NULL, NULL),
  ('야무지', 'land4968', '촉나라', '꾸한성', '일반 병사', FALSE, NULL, NULL),
  ('엔쥬', 'northpole', '촉나라', '꾸한성', '일반 병사', FALSE, NULL, NULL),
  ('윤타미', 'dbsthdus111', '촉나라', '꾸한성', '일반 병사', FALSE, NULL, NULL),
  ('임민트', 'mint616', '촉나라', '꾸한성', '일반 병사', FALSE, NULL, NULL),
  ('지피티', 'tjrdbs999', '오나라', '지력사무소', '군주', FALSE, NULL, NULL),
  ('가습기', 'hwt1014', '오나라', '가무소', '장군', FALSE, NULL, NULL),
  ('기찬하', 'khj011219', '오나라', '가무소', '일반 병사', FALSE, NULL, NULL),
  ('단수아', 'tndk321', '오나라', '가무소', '일반 병사', FALSE, NULL, NULL),
  ('딩굴', 'dinggoolx3', '오나라', '가무소', '일반 병사', FALSE, NULL, NULL),
  ('새잎', 'likey0u', '오나라', '가무소', '일반 병사', FALSE, NULL, NULL),
  ('야뿌', 'ekrekrnfl9', '오나라', '가무소', '일반 병사', FALSE, NULL, NULL),
  ('연보라', '200501', '오나라', '가무소', '일반 병사', FALSE, NULL, NULL),
  ('연치민', 'yeonchimin', '오나라', '가무소', '일반 병사', FALSE, NULL, NULL),
  ('희꾸미', 'ddr9463', '오나라', '가무소', '일반 병사', FALSE, NULL, NULL),
  ('홍타쿠', 'lhtlgm', '오나라', '홍피스', '장군', FALSE, NULL, NULL),
  ('따스히', 'guqlswls123', '오나라', '홍피스', '일반 병사', FALSE, NULL, NULL),
  ('현단아', 'hyundana', '오나라', '홍피스', '일반 병사', FALSE, NULL, NULL)
ON CONFLICT (nickname) DO UPDATE
SET
  soop_id = EXCLUDED.soop_id,
  nation = EXCLUDED.nation,
  crew_name = EXCLUDED.crew_name,
  role_name = EXCLUDED.role_name,
  is_live = EXCLUDED.is_live,
  thumbnail_image_url = EXCLUDED.thumbnail_image_url,
  profile_image_url = EXCLUDED.profile_image_url,
  updated_at = NOW();
